export const AUTH_INIT = 'AUTH_INIT';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_NOTLOGOUT = 'SET_NOTLOGOUT';

export const RESET_PSWD_START = 'RESET_PSWD_START';
export const RESET_PSWD_SUCCESS = 'RESET_PSWD_SUCCESS';
export const RESET_PSWD_FAIL = 'RESET_PSWD_FAIL';
export const CLEAR_ERROR = 'CLEAR_ERROR';

export const WINDOW_RESIZE = 'WINDOW_RESIZE';

export const GET_MEALS_START = 'GET_MEALS_START';
export const GET_MEALS_SUCCESS = 'GET_MEALS_SUCCESS';
export const GET_MEALS_FAIL = 'GET_MEALS_FAIL';
export const GET_MEAL_START = 'GET_MEAL_START';
export const GET_MEAL_SUCCESS = 'GET_MEAL_SUCCESS';
export const GET_MEAL_FAIL = 'GET_MEAL_FAIL';

export const GET_INGRED_START = 'GET_INGRED_START';
export const GET_INGRED_SUCCESS = 'GET_INGRED_SUCCESS';
export const GET_INGRED_FAIL = 'GET_INGRED_FAIL';

export const ADD_MEAL_START = 'ADD_MEAL_START';
export const ADD_MEAL_SUCCESS = 'ADD_MEAL_SUCCESS';
export const ADD_MEAL_FAIL = 'ADD_MEAL_FAIL';

export const DELETE_MEAL_START = 'DELETE_MEAL_START';
export const DELETE_MEAL_SUCCESS = 'DELETE_MEAL_SUCCESS';
export const DELETE_MEAL_FAIL = 'DELETE_MEAL_FAIL';

export const GET_SHOPPING_LIST_START = 'GET_SHOPPING_LIST_START';
export const GET_SHOPPING_LIST_SUCCESS = 'GET_SHOPPING_LIST_SUCCESS';
export const GET_SHOPPING_LIST_FAIL = 'GET_SHOPPING_LIST_FAIL';

export const DELETE_SHOPPING_LIST_START = 'DELETE_SHOPPING_LIST_START';
export const DELETE_SHOPPING_LIST_SUCCESS = 'DELETE_SHOPPING_LIST_SUCCESS';
export const DELETE_SHOPPING_LIST_FAIL = 'DELETE_SHOPPING_LIST_FAIL';

export const ADD_SHOPPING_ITEM_START = 'ADD_SHOPPING_ITEM_START';
export const ADD_SHOPPING_ITEM_SUCCESS = 'ADD_SHOPPING_ITEM_SUCCESS';
export const ADD_SHOPPING_ITEM_FAIL = 'ADD_SHOPPING_ITEM_FAIL';

export const DELETE_SHOPPING_ITEM_START = 'DELETE_SHOPPING_ITEM_START';
export const DELETE_SHOPPING_ITEM_SUCCESS = 'DELETE_SHOPPING_ITEM_SUCCESS';
export const DELETE_SHOPPING_ITEM_FAIL = 'DELETE_SHOPPING_ITEM_FAIL';

export const GENERATE_SHOPPING_LIST_START = 'GENERATE_SHOPPING_LIST_START';
export const GENERATE_SHOPPING_LIST_SUCCESS = 'GENERATE_SHOPPING_LIST_SUCCESS';
export const GENERATE_SHOPPING_LIST_FAIL = 'GENERATE_SHOPPING_LIST_FAIL';

export const SAVE_SHOPPING_LIST_START = 'SAVE_SHOPPING_LIST_START';
export const SAVE_SHOPPING_LIST_SUCCESS = 'SAVE_SHOPPING_LIST_SUCCESS';
export const SAVE_SHOPPING_LIST_FAIL = 'SAVE_SHOPPING_LIST_FAIL';

export const GET_DIET_START = 'GET_DIET_START';
export const GET_DIET_SUCCESS = 'GET_DIET_SUCCESS';
export const GET_DIET_FAIL = 'GET_DIET_FAIL';

export const ADD_CARD_START = 'ADD_CARD_START';
export const ADD_CARD_SUCCESS = 'ADD_CARD_SUCCESS';
export const ADD_CARD_FAIL = 'ADD_CARD_FAIL';

export const DELETE_CARD_START = 'DELETE_CARD_START';
export const DELETE_CARD_SUCCESS = 'DELETE_CARD_SUCCESS';
export const DELETE_CARD_FAIL = 'DELETE_CARD_FAIL';

export const ADD_CARD_MEAL_START = 'ADD_CARD_MEAL_START';
export const ADD_CARD_MEAL_SUCCESS = 'ADD_CARD_MEAL_SUCCESS';
export const ADD_CARD_MEAL_FAIL = 'ADD_CARD_MEAL_FAIL';
